# Generated by Django 3.0.8 on 2020-07-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='image'),
        ),
    ]
